#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 18 22:44:43 2022
Visualizing Data from MEPS HC-2019 file to prep for interview
@author: brandanclark
"""


#install packages logic run in Terminal
"""
pip install pandas
pip install plotly
"""
#import packages
import plotly.express as px
import pandas as pd

#add plotly offline to allow for plot() functionality
from plotly.offline import plot

#create df reading file
df= pd.read_csv("/Users/brandanclark/Downloads/h219.csv")

#drop duplicates
df.drop_duplicates(inplace=True)

#new dataframe removing bad data from ADHDAGED column
filtered_df = df.loc[df['ADHDAGED'] > 0]

#create pie chart
pie_fig = px.pie(
    data_frame=filtered_df,
    names='ADHDAGED',
    hole=0.0,
    title='Age of ADHD Diagnosis')

#create bar chart
bar_fig = px.bar(
    data_frame=filtered_df.groupby(["ADHDAGED"], as_index=False).agg(count=pd.NamedAgg(column="ADHDAGED", aggfunc="count")),
    x='ADHDAGED',
    y='count',
    color='ADHDAGED',
    title='ADHD Diagnosis by Age')

#show charts
plot(pie_fig)
plot(bar_fig)

